[package]
name = "rubete"
version = "0.1.0"
edition = "2024"

[dependencies]
ntex = { version = "2.0", features = ["tokio"] }
serde_json = "1.0"
dotenvy = "0.15"
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
